### model
model_name_or_path: mistralai/Mistral-7B-Instruct-v0.2

### TODO: Parameters that Need to customize
dataset: Feedback-Collection_score_only_train
eval_dataset: Feedback-Collection_score_only_validation
output_dir: saves/mistral-7b/lora/raft/score_only
### The effective batch size should be 64
per_device_train_batch_size: 4
gradient_accumulation_steps: 16

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
template: mistral
cutoff_len: 4096
overwrite_cache: true
preprocessing_num_workers: 16

### output
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
learning_rate: 1.0e-5
num_train_epochs: 5.0
lr_scheduler_type: constant
bf16: true
ddp_timeout: 180000000

### eval
eval_strategy: epoch
per_device_eval_batch_size: 1