### Note: DO NOT use quantized model or quantization_bit when merging lora adapters

### model
model_name_or_path: mistralai/Mistral-7B-Instruct-v0.2
adapter_name_or_path: saves/mistral-7b/lora/cot_single_and_pair
template: mistral
finetuning_type: lora
trust_remote_code: true

### export
export_dir: /home/dcml0714/raft_llm_as_a_judge/models/mistral-7b/lora/cot_single_and_pair
export_size: 2
export_device: cpu
export_legacy_format: false
